language: javascript

cache:
  directories:
    - "travis_phantomjs"

before_install:
  - mkdir qunit
  - wget -O qunit/qunit-1.18.0.css http://code.jquery.com/qunit/qunit-1.18.0.css
  - wget -O qunit/qunit-1.18.0.js  http://code.jquery.com/qunit/qunit-1.18.0.js
  - npm install testem

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - chmod a+x scripts/ensure_phantomjs.sh
  - scripts/ensure_phantomjs.sh
  - export PATH=$PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH

script:
  - ./node_modules/.bin/testem -t www/tests/qunit/run_tests.html ci
  #- phantomjs phantomjs/examples/run-qunit.js www/tests/qunit/run_tests.html

